/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mocks from "./mocks";
export { SIGProfitDistributor__factory } from "./SIGProfitDistributor__factory";
