/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SIGProfitDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_PAYEES"
      | "acceptOwnership"
      | "claimNative"
      | "claimNativeFor"
      | "claimToken"
      | "claimTokenFor"
      | "claimable"
      | "claimedBy"
      | "closeDeposits"
      | "currentBalance"
      | "depositNative"
      | "depositToken"
      | "depositsClosed"
      | "freezeShares"
      | "owner"
      | "payeeAt"
      | "payeeCount"
      | "payees"
      | "pendingOwner"
      | "renounceOwnership"
      | "rescueUntrackedNative"
      | "rescueUntrackedToken"
      | "setPayees"
      | "shareBps"
      | "sharesFrozen"
      | "totalClaimed"
      | "totalReceived"
      | "trackedBalance"
      | "transferOwnership"
      | "untrackedBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositsClosed"
      | "NativeClaimed"
      | "NativeDeposited"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "PayeesSet"
      | "SharesFrozen"
      | "TokenClaimed"
      | "TokenDeposited"
      | "UntrackedNativeRescued"
      | "UntrackedTokenRescued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PAYEES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimNativeFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokenFor",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedBy",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeDeposits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositsClosed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "freezeShares",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payeeAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "payeeCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "payees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueUntrackedNative",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueUntrackedToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPayees",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "shareBps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesFrozen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReceived",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trackedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "untrackedBalance",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_PAYEES", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimNativeFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimTokenFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimedBy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositsClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payeeAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payeeCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueUntrackedNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueUntrackedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPayees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shareBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sharesFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trackedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "untrackedBalance",
    data: BytesLike
  ): Result;
}

export namespace DepositsClosedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeClaimedEvent {
  export type InputTuple = [payee: AddressLike, amount: BigNumberish];
  export type OutputTuple = [payee: string, amount: bigint];
  export interface OutputObject {
    payee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeDepositedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayeesSetEvent {
  export type InputTuple = [payees: AddressLike[], sharesBps: BigNumberish[]];
  export type OutputTuple = [payees: string[], sharesBps: bigint[]];
  export interface OutputObject {
    payees: string[];
    sharesBps: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesFrozenEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenClaimedEvent {
  export type InputTuple = [
    payee: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [payee: string, token: string, amount: bigint];
  export interface OutputObject {
    payee: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDepositedEvent {
  export type InputTuple = [
    from: AddressLike,
    token: AddressLike,
    amountReceived: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    token: string,
    amountReceived: bigint
  ];
  export interface OutputObject {
    from: string;
    token: string;
    amountReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UntrackedNativeRescuedEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UntrackedTokenRescuedEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SIGProfitDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): SIGProfitDistributor;
  waitForDeployment(): Promise<this>;

  interface: SIGProfitDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_PAYEES: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  claimNative: TypedContractMethod<[], [void], "nonpayable">;

  claimNativeFor: TypedContractMethod<
    [payee: AddressLike],
    [void],
    "nonpayable"
  >;

  claimToken: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  claimTokenFor: TypedContractMethod<
    [token: AddressLike, payee: AddressLike],
    [void],
    "nonpayable"
  >;

  claimable: TypedContractMethod<
    [asset: AddressLike, payee: AddressLike],
    [bigint],
    "view"
  >;

  claimedBy: TypedContractMethod<
    [asset: AddressLike, payee: AddressLike],
    [bigint],
    "view"
  >;

  closeDeposits: TypedContractMethod<[], [void], "nonpayable">;

  currentBalance: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  depositNative: TypedContractMethod<[], [void], "payable">;

  depositToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositsClosed: TypedContractMethod<[], [boolean], "view">;

  freezeShares: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  payeeAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  payeeCount: TypedContractMethod<[], [bigint], "view">;

  payees: TypedContractMethod<[], [string[]], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueUntrackedNative: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rescueUntrackedToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPayees: TypedContractMethod<
    [accounts: AddressLike[], bpsValues: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  shareBps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  sharesFrozen: TypedContractMethod<[], [boolean], "view">;

  totalClaimed: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  totalReceived: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  trackedBalance: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  untrackedBalance: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PAYEES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNative"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNativeFor"
  ): TypedContractMethod<[payee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTokenFor"
  ): TypedContractMethod<
    [token: AddressLike, payee: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<
    [asset: AddressLike, payee: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimedBy"
  ): TypedContractMethod<
    [asset: AddressLike, payee: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeDeposits"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentBalance"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositNative"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositsClosed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "freezeShares"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payeeAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "payeeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "payees"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueUntrackedNative"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueUntrackedToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPayees"
  ): TypedContractMethod<
    [accounts: AddressLike[], bpsValues: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shareBps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sharesFrozen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalClaimed"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReceived"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "trackedBalance"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "untrackedBalance"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  getEvent(
    key: "DepositsClosed"
  ): TypedContractEvent<
    DepositsClosedEvent.InputTuple,
    DepositsClosedEvent.OutputTuple,
    DepositsClosedEvent.OutputObject
  >;
  getEvent(
    key: "NativeClaimed"
  ): TypedContractEvent<
    NativeClaimedEvent.InputTuple,
    NativeClaimedEvent.OutputTuple,
    NativeClaimedEvent.OutputObject
  >;
  getEvent(
    key: "NativeDeposited"
  ): TypedContractEvent<
    NativeDepositedEvent.InputTuple,
    NativeDepositedEvent.OutputTuple,
    NativeDepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayeesSet"
  ): TypedContractEvent<
    PayeesSetEvent.InputTuple,
    PayeesSetEvent.OutputTuple,
    PayeesSetEvent.OutputObject
  >;
  getEvent(
    key: "SharesFrozen"
  ): TypedContractEvent<
    SharesFrozenEvent.InputTuple,
    SharesFrozenEvent.OutputTuple,
    SharesFrozenEvent.OutputObject
  >;
  getEvent(
    key: "TokenClaimed"
  ): TypedContractEvent<
    TokenClaimedEvent.InputTuple,
    TokenClaimedEvent.OutputTuple,
    TokenClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TokenDeposited"
  ): TypedContractEvent<
    TokenDepositedEvent.InputTuple,
    TokenDepositedEvent.OutputTuple,
    TokenDepositedEvent.OutputObject
  >;
  getEvent(
    key: "UntrackedNativeRescued"
  ): TypedContractEvent<
    UntrackedNativeRescuedEvent.InputTuple,
    UntrackedNativeRescuedEvent.OutputTuple,
    UntrackedNativeRescuedEvent.OutputObject
  >;
  getEvent(
    key: "UntrackedTokenRescued"
  ): TypedContractEvent<
    UntrackedTokenRescuedEvent.InputTuple,
    UntrackedTokenRescuedEvent.OutputTuple,
    UntrackedTokenRescuedEvent.OutputObject
  >;

  filters: {
    "DepositsClosed()": TypedContractEvent<
      DepositsClosedEvent.InputTuple,
      DepositsClosedEvent.OutputTuple,
      DepositsClosedEvent.OutputObject
    >;
    DepositsClosed: TypedContractEvent<
      DepositsClosedEvent.InputTuple,
      DepositsClosedEvent.OutputTuple,
      DepositsClosedEvent.OutputObject
    >;

    "NativeClaimed(address,uint256)": TypedContractEvent<
      NativeClaimedEvent.InputTuple,
      NativeClaimedEvent.OutputTuple,
      NativeClaimedEvent.OutputObject
    >;
    NativeClaimed: TypedContractEvent<
      NativeClaimedEvent.InputTuple,
      NativeClaimedEvent.OutputTuple,
      NativeClaimedEvent.OutputObject
    >;

    "NativeDeposited(address,uint256)": TypedContractEvent<
      NativeDepositedEvent.InputTuple,
      NativeDepositedEvent.OutputTuple,
      NativeDepositedEvent.OutputObject
    >;
    NativeDeposited: TypedContractEvent<
      NativeDepositedEvent.InputTuple,
      NativeDepositedEvent.OutputTuple,
      NativeDepositedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayeesSet(address[],uint256[])": TypedContractEvent<
      PayeesSetEvent.InputTuple,
      PayeesSetEvent.OutputTuple,
      PayeesSetEvent.OutputObject
    >;
    PayeesSet: TypedContractEvent<
      PayeesSetEvent.InputTuple,
      PayeesSetEvent.OutputTuple,
      PayeesSetEvent.OutputObject
    >;

    "SharesFrozen()": TypedContractEvent<
      SharesFrozenEvent.InputTuple,
      SharesFrozenEvent.OutputTuple,
      SharesFrozenEvent.OutputObject
    >;
    SharesFrozen: TypedContractEvent<
      SharesFrozenEvent.InputTuple,
      SharesFrozenEvent.OutputTuple,
      SharesFrozenEvent.OutputObject
    >;

    "TokenClaimed(address,address,uint256)": TypedContractEvent<
      TokenClaimedEvent.InputTuple,
      TokenClaimedEvent.OutputTuple,
      TokenClaimedEvent.OutputObject
    >;
    TokenClaimed: TypedContractEvent<
      TokenClaimedEvent.InputTuple,
      TokenClaimedEvent.OutputTuple,
      TokenClaimedEvent.OutputObject
    >;

    "TokenDeposited(address,address,uint256)": TypedContractEvent<
      TokenDepositedEvent.InputTuple,
      TokenDepositedEvent.OutputTuple,
      TokenDepositedEvent.OutputObject
    >;
    TokenDeposited: TypedContractEvent<
      TokenDepositedEvent.InputTuple,
      TokenDepositedEvent.OutputTuple,
      TokenDepositedEvent.OutputObject
    >;

    "UntrackedNativeRescued(address,uint256)": TypedContractEvent<
      UntrackedNativeRescuedEvent.InputTuple,
      UntrackedNativeRescuedEvent.OutputTuple,
      UntrackedNativeRescuedEvent.OutputObject
    >;
    UntrackedNativeRescued: TypedContractEvent<
      UntrackedNativeRescuedEvent.InputTuple,
      UntrackedNativeRescuedEvent.OutputTuple,
      UntrackedNativeRescuedEvent.OutputObject
    >;

    "UntrackedTokenRescued(address,address,uint256)": TypedContractEvent<
      UntrackedTokenRescuedEvent.InputTuple,
      UntrackedTokenRescuedEvent.OutputTuple,
      UntrackedTokenRescuedEvent.OutputObject
    >;
    UntrackedTokenRescued: TypedContractEvent<
      UntrackedTokenRescuedEvent.InputTuple,
      UntrackedTokenRescuedEvent.OutputTuple,
      UntrackedTokenRescuedEvent.OutputObject
    >;
  };
}
